### ISSUE TITLE
加个分类页面？

### ISSUE THREAD

**Issue by jerry011235** [KevinOfNeu/hexo-theme-xxoo#1]
或者在`tag.ejs`中直接把分类加在后面也可。
另外评论可用 https://valine.js.org/

**Comment by Holdge** [comment]
@jerry011235 分类页没考虑清楚，很多场景下，分类和tag会混用，不如直接 tag 来得方便。你可以改下试试，看看效果。
评论的话看个人喜好，我不在被墙😄
