### ISSUE TITLE
搜索页咋配？

### ISSUE THREAD

**Issue by az031120103** [KevinOfNeu/hexo-theme-xxoo#2]

**Comment by Holdge** [comment]
source 下新建一个 search 目录，里面放一个 index.md 文件，内容如下
```
---
  title: Search
  date: 2016-05-24 13:45:13
  type: "search"
---
```

**Comment by az031120103** [comment]
source 下的 search 目录
另外在 _config.yml 文件加了一行 search_dir: search
hexo g 构建报错

>/study/hexo/blog/themes/xoxo/layout/partials/scripts.ejs:122
var search_path = "<%= config.search.path %>";
if (search_path.length == 0) {
    search_path = "search.xml";
}

**Comment by ubuntuvim** [comment]
@az031120103 哥们你怎么解决这个报错的？

```html
    120|         });
    121|       };
 >> 122|       var search_path = "<%= config.search.path %>";
    123|       if (search_path.length == 0) {
    124|         search_path = "search.xml";
    125|       }
```

**Comment by shenzekun** [comment]
@ubuntuvim @az031120103 得在非主题的配置文件 config_yml，配置如下:
```
search:
  path: search.xml
  field: post
```
而不是配置在主题的配置文件里, 文档写错了，建议博主改一下，代码里面明显写的是 config.search 而不是 theme.search，应该是把 search 的配置写在非主题配置文件里面，而不是主题配置文件里面@KevinOfNeu

**Comment by Holdge** [comment]
@shenzekun 多谢
