### ISSUE TITLE
访问页面报错

### ISSUE THREAD

**Issue by ubuntuvim** [KevinOfNeu/hexo-theme-xxoo#3]
```shell
Unhandled rejection ReferenceError: /themes/hexo-theme-xoxo/layout/post.ejs:28
    26|     </span>
    27|       <span class="slash">/</span>
 >> 28|       <!-- <span class="read">阅读耗时 <%=readingTime(page.content, '分钟') %></span> -->
    29|     </header>
    30| 
    31|     <div class="post-content">

readingTime is not defined
```
`readingTime`方法找不到。

另外你的博客中搜索功能是自己另外开发的吧？并不包含在这个主题中？

**Comment by Holdge** [comment]
themes/hexo-theme-xoxo/node_modules/hexo-reading-time/index.js:
    1  'use strict';
    2  
    3: hexo.extend.helper.register('readingTime', require('./lib/readingtime'));
    4  
readTime 在这里定义，需要 npm install

搜索是主题中的

**Comment by freewangv** [comment]
themes/hexo-theme-xoxo/node_modules/hexo-reading-time/index.js:
1 'use strict';
2
3: hexo.extend.helper.register('readingTime', require('./lib/readingtime'));
4
readTime 在这里定义，需要 npm install

搜索是主题中的

@KevinOfNeu 不是 themes/ 目录下，应该是 主目录的 node_modules/hexo-reading-time/index.js:

检查了下，我的 node_modules/hexo-reading-time/index.js 存在，也还是有如下错误：

ReferenceError: D:\Blog\themes\xoxo\layout\post.ejs:28
\>\> 28\|      \<span class="read"\>阅读耗时 \<%=readingTime(page.content, '分钟') %\>\<\/span\>

readingTime is not defined

**Comment by blueskea** [comment]
`npm install hexo-reading-time --save`
and it's ok
