### ISSUE TITLE
busuanzi 改域名了

### ISSUE THREAD

**Issue by hjweix** [KevinOfNeu/hexo-theme-xxoo#4]
在用这个主题时发现点击数出不来，去[不蒜子](http://ibruce.info/2015/04/04/busuanzi/)网站看了下，9月份更换了域名了。
把head.ejs 中的
``` 
dn-lbstatics.qbox.me
```
修改成了
```
 busuanzi.ibruce.info
```
不得不说主题很棒！

**Comment by Holdge** [comment]
@hjwjw 多谢提醒
