### ISSUE TITLE
图片的设置

### ISSUE THREAD

**Issue by prayjourney** [KevinOfNeu/hexo-theme-xxoo#7]
问一下我怎么设置我的头像, 以及网站的favorite的小图标?

**Comment by GeorgeWang20** [comment]
我也遇到这个问题了，请问解决了吗

**Comment by wl1991** [comment]
头像设置：需要配置最外层hexo的config .yml里的：url: http://localhost:4000（网站url）。
网站的小图标：修改head.ejs文件里的： <link rel="icon" href="<%- theme.favicon %>" type="image/x-icon">，修改原href的值，然后配置该theme文件里的config.yml里的favicon。
